version: '3'

services:
  db:
    image: docker-magento-multiple-db_db
    environment:
      MYSQL_ROOT_PASSWORD: magento
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 2125:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    depends_on:
      - db
    networks:
      - webnet

networks:
  webnet:
